### ISSUE TITLE
Filter-Functionality in Search

### ISSUE THREAD

**Issue by jacobrhn** [loiicd/portfolio-webprogrammierung#10]
Es gibt eine Möglichkeit, die Suche zu filtern (mit Auswahlliste/Dropdown, Checkbox oder Radiobutton).

**Comment by loiicd** [comment]
can u agree @jacobrhn

**Comment by jacobrhn** [comment]
hi @loiicd . the functionality is now given great job. 🌭

for a future release I would like to see the sizing of filter box the same as the search bar (with rounded corners) and the search bar it self also border.


Will take it with me to next backlog refinement.

Great Job Team!
